name: Terraform Infra Deploy workflow
run-name: Terraform Infra Deploy CI
on:  
  schedule:
    - cron: '50 6 * * 1-5'
  # push:
  #   branches:
  #     - 'main'   
jobs:
    DeployInfra:
        name: Deploy Infra
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@master
            - name: Deploy infra
              uses: "./.github/template/apply"
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                admin_sa_key: ${{ secrets.ADMIN_SA_KEY }}
                compute_engine_sa_key: ${{ secrets.COMPUTE_ENGINE_SA_KEY }}
                action: apply
