name: Terraform Infra Destroy workflow
run-name: Terraform Infra Destroy CI
on:
  schedule:
    - cron: '30 18 * * *' 
env:
  CLUSTER_NAME: dockercoins-cluster-teo
  CLUSTER_ZONE: europe-west1-b
  PROJECT_NAME: teolia-school-devops

jobs:
    deleteGKEIngressInfra:
      name: Destroy GKE ingress infra(Ingress, LB, NEG & Certificate which blocks vpc destruction)
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@master
          with:
            repository: 'AmineBouzayeni/DockerCoinsApp'
            ref: 'feature/abouzayeni/TA-19'
        - name: Install gcloud authentication plugin
          run: |
            REPO_URL="https://packages.cloud.google.com/apt"
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] $REPO_URL cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list >/dev/null
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
      
            sudo apt-get update -y
            sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
      
        - name: Authenticate to Google Cloud
          uses: 'google-github-actions/auth@v1'
          with:
            credentials_json: '${{ secrets.ADMIN_KEY }}'
            token_format: 'access_token'
          
        - name: Authenticate to GKE cluster
          run: |   
            gcloud container clusters get-credentials \
            ${{ env.CLUSTER_NAME }} --zone ${{ env.CLUSTER_ZONE }} --project ${{ env.PROJECT_NAME }}    
        
        - name: Destroy Ingress Infra
          run: |
            if [[ $(kubectl get ingress -n app | grep -c managed-cert-ingress) == 0 ]]
              then
                echo "No ingress resource in app namespace. Skipping."
            else    
              kubectl delete -f manifests/prod/ingress-manifest.yml
            fi  

    destroyInfra:
        name: Destroy Infra
        runs-on: ubuntu-latest
        needs: [deleteGKEIngressInfra]
        steps:
            - name: Checkout code
              uses: actions/checkout@master
            - name: Destroy infra
              uses: "./.github/template/apply"
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                admin_sa_key: ${{ secrets.ADMIN_SA_KEY }}
                compute_engine_sa_key: ${{ secrets.COMPUTE_ENGINE_SA_KEY }}
                action: destroy

